version: '3.8'
services:
  postgresdb:
    image: postgres:16.1-alpine3.18
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - app-network

  expressapp:
    build: ./data_query
    ports:
      - "3000:3000"
    depends_on:
      - postgresdb
    environment:
      - DB_HOST=postgresdb
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=${DB_DATABASE}
      - DB_PORT=${DB_PORT}
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db-data: